name: Daily Pattern Scanner - Simple (Ubuntu Package)

on:
  schedule:
    # Run at 4:30 PM ET daily (after market close)
    - cron: '30 20 * * 1-5'  # EST: 4:30 PM ET
    - cron: '30 21 * * 1-5'  # EDT: 4:30 PM ET
  
  workflow_dispatch:  # Allow manual trigger
    inputs:
      tickers:
        description: 'Comma-separated list of tickers (default: all)'
        required: false
        default: 'NVDA,AAPL,MSFT,BTC-USD,AC.TO'
        type: string

jobs:
  scan-daily-patterns:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ticker: [NVDA, AAPL, MSFT, BTC-USD, AC.TO]
      fail-fast: false  # Continue other tickers even if one fails
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install TA-Lib using Ubuntu packages
      run: |
        # Install TA-Lib using Ubuntu package manager (more reliable)
        sudo apt-get update
        sudo apt-get install -y libta-lib0-dev
        
        # Verify system installation
        echo "Checking TA-Lib installation..."
        ls -la /usr/include/ta-lib/ || echo "Headers not found"
        ls -la /usr/lib/x86_64-linux-gnu/libta_lib* || echo "Library not found"
        pkg-config --exists ta-lib && echo "TA-Lib found via pkg-config" || echo "TA-Lib not found via pkg-config"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        
        # Install other dependencies first
        pip install yfinance pandas numpy azure-storage-blob python-dotenv
        
        # Install TA-Lib Python wrapper (should work with system TA-Lib)
        pip install TA-Lib
        
        # Verify installation
        python -c "import talib; print(f'TA-Lib version: {talib.__version__}')"
    
    - name: Create config directory and .env file
      run: |
        mkdir -p config
        cat > config/.env << EOF
        AZURE_STORAGE_ACCOUNT=${{ secrets.STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_KEY=${{ secrets.ACCESS_KEY }}
        AZURE_CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}
        EOF
    
    - name: Run daily pattern scanner for ${{ matrix.ticker }}
      run: |
        export TICKER="${{ matrix.ticker }}"
        python daily_pattern_scanner.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.ticker }}-daily-pattern-logs-${{ github.run_id }}
        path: |
          *.log
          *.json
        if-no-files-found: warn
        retention-days: 7

  performance-summary:
    runs-on: ubuntu-latest
    needs: scan-daily-patterns
    # Run at 4:45 PM ET daily to generate performance report (after all scans complete)
    if: |
      github.event_name == 'schedule' && 
      (contains(github.event.schedule, '45 20') || contains(github.event.schedule, '45 21'))
    
    strategy:
      matrix:
        ticker: [NVDA, AAPL, MSFT, BTC-USD, AC.TO]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas azure-storage-blob python-dotenv
    
    - name: Create config directory and .env file
      run: |
        mkdir -p config
        cat > config/.env << EOF
        AZURE_STORAGE_ACCOUNT=${{ secrets.STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_KEY=${{ secrets.ACCESS_KEY }}
        AZURE_CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}
        EOF
    
    - name: Generate performance summary for ${{ matrix.ticker }}
      run: |
        export TICKER="${{ matrix.ticker }}"
        python -c "
        from daily_pattern_scanner import DailyPatternScanner
        scanner = DailyPatternScanner(ticker='${{ matrix.ticker }}')
        evaluations = scanner.load_or_create_evaluation_file()
        total_evals = len(evaluations)
        if total_evals > 0:
            recent_evals = evaluations[-30:] if total_evals > 30 else evaluations
            buy_signals = sum(1 for e in recent_evals if e.get('recommendation') == 'BUY')
            sell_signals = sum(1 for e in recent_evals if e.get('recommendation') == 'SELL')
            hold_signals = sum(1 for e in recent_evals if e.get('recommendation') == 'HOLD')
            avg_confidence = sum(e.get('confidence', 0) for e in recent_evals) / len(recent_evals)
            print('${{ matrix.ticker }} Daily Pattern Summary (Last 30 days):')
            print(f'Total Evaluations: {len(recent_evals)}')
            print(f'Buy: {buy_signals}, Sell: {sell_signals}, Hold: {hold_signals}')
            print(f'Average Confidence: {avg_confidence:.1%}')
        else:
            print('No evaluation data available yet')
        "
    
    - name: Create issue with daily summary
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const date = new Date().toISOString().split('T')[0];
          const ticker = '${{ matrix.ticker }}';
          const tickerLower = ticker.toLowerCase().replace('-', '');
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Daily Pattern Scanner Summary - ${ticker} - ${date}`,
            body: `Today's ${ticker} daily chart patterns have been analyzed. Check the next_day_technical/${tickerLower}/ folder in Azure for detailed predictions.`,
            labels: ['automated', 'daily-report', 'pattern-scanner', tickerLower]
          });