name: Fetch Market Data

on:
  schedule:
    # Run every minute during market hours (9:30 AM to 4:00 PM EST)
    # UTC times: 14:30 to 21:00 (EST is UTC-5 in winter, UTC-4 in summer)
    - cron: '*/1 14-20 * * 1-5'  # Every minute from 2:30 PM to 8:59 PM UTC on weekdays
    - cron: '0-30 21 * * 1-5'     # Every minute from 9:00 PM to 9:30 PM UTC on weekdays
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
    - name: Install R dependencies
      run: |
        Rscript -e "install.packages(c('reticulate', 'dplyr', 'arrow', 'readr', 'lubridate', 'AzureStor'), repos='https://cloud.r-project.org/')"
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run data fetching script
      env:
        TICKERS: ${{ secrets.TICKERS }}
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
        AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      run: |
        Rscript raw_data.R