name: Fetch Hourly and Daily Data

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'  # At minute 0 of every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-hourly-daily-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install azure-storage-blob
    
    - name: Run hourly and daily data fetching script
      env:
        TICKERS: ${{ secrets.TICKERS }}
        STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PWD: ${{ secrets.GMAIL_APP_PWD }}
        ALERT_TO: ${{ secrets.ALERT_TO }}
      run: |
        python fetch_hourly_daily_data.py