name: Fetch Market Data

on:
  schedule:
    # Run every minute during market hours (9:30 AM to 4:00 PM EST)
    # UTC times: 14:30 to 21:00 (EST is UTC-5 in winter, UTC-4 in summer)
    - cron: '*/1 14-20 * * 1-5'  # Every minute from 2:30 PM to 8:59 PM UTC on weekdays
    - cron: '0-30 21 * * 1-5'     # Every minute from 9:00 PM to 9:30 PM UTC on weekdays
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.3.0
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Setup Python
      run: |
        apt-get update && apt-get install -y python3-pip python3-dev python3-venv
        
    - name: Cache R packages
      uses: actions/cache@v3
      id: cache-r-packages
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ runner.os }}-r-packages-v3-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-r-packages-v3-
    
    - name: Cache Python packages
      uses: actions/cache@v3
      id: cache-python-packages
      with:
        path: /usr/local/lib/python3.*/dist-packages
        key: ${{ runner.os }}-python-packages-v1-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-packages-v1-
          
    - name: Install R dependencies
      if: steps.cache-r-packages.outputs.cache-hit != 'true'
      run: |
        Rscript -e "install.packages(c('reticulate', 'arrow', 'AzureStor'), repos='https://cloud.r-project.org/')"
        
    - name: Install Python dependencies
      if: steps.cache-python-packages.outputs.cache-hit != 'true'
      run: |
        pip3 install -r requirements.txt
        
    - name: Run data fetching script
      env:
        TICKERS: ${{ secrets.TICKERS }}
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
        AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      run: |
        Rscript raw_data.R