name: Multi-Ticker Signal Analysis

on:
  schedule:
    # Run every 2 hours during market hours (9:30 AM - 4:00 PM ET)
    # Market hours: 14:30-21:00 UTC (9:30 AM - 4:00 PM ET)
    - cron: '30 14,16,18,20 * * 1-5'  # Monday-Friday at 14:30, 16:30, 18:30, 20:30 UTC
  workflow_dispatch:  # Allow manual triggering

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
  AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}

jobs:
  multi-ticker-signal-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy yfinance azure-storage-blob python-dotenv pyyaml
        
    - name: Create config directory and .env file
      run: |
        mkdir -p config
        echo "AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }}" >> config/.env
        echo "AZURE_STORAGE_KEY=${{ secrets.AZURE_STORAGE_KEY }}" >> config/.env
        echo "AZURE_CONTAINER_NAME=${{ secrets.AZURE_CONTAINER_NAME }}" >> config/.env
        
    - name: Run Multi-Ticker Signal Analysis
      run: |
        cd technical
        python multi_ticker_signal_analyzer.py
        
    - name: Check Azure upload
      if: always()
      run: |
        echo "Multi-ticker signal analysis completed"
        echo "Results should be uploaded to Azure Storage under signal_analysis/ folder"
        
    - name: Cleanup
      if: always()
      run: |
        rm -f config/.env