name: Test Email Alerts

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-email:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Test email configuration
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PWD: ${{ secrets.GMAIL_APP_PWD }}
        ALERT_TO: ${{ secrets.ALERT_TO }}
      run: |
        echo "Testing email configuration..."
        python quick_email_test.py
        
    - name: Run comprehensive email test
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PWD: ${{ secrets.GMAIL_APP_PWD }}
        ALERT_TO: ${{ secrets.ALERT_TO }}
      run: |
        # Auto-confirm the test
        echo "y" | python test_email_alert.py