name: Test Setup

on:
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.3'
    
    - name: Test R installation
      run: |
        Rscript -e "R.version.string"
        Rscript -e "installed.packages()[,'Package']"
    
    - name: Install required packages
      run: |
        Rscript -e "install.packages(c('dplyr', 'stringr', 'readr'), repos='https://cran.r-project.org')"
        Rscript -e "install.packages('RedditExtractoR', repos='https://cran.r-project.org')"
        Rscript -e "library(RedditExtractoR); cat('RedditExtractoR loaded successfully\n')"
    
    - name: Test Azure CLI
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_KEY: ${{ secrets.ACCESS_KEY }}
        AZURE_CONTAINER: ${{ secrets.CONTAINER_NAME }}
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        
        echo "Testing Azure connection..."
        az storage container exists \
          --account-name "$AZURE_STORAGE_ACCOUNT" \
          --account-key "$AZURE_STORAGE_KEY" \
          --name "$AZURE_CONTAINER" && echo "✅ Azure container accessible" || echo "❌ Cannot access Azure container"
    
    - name: Create test data
      run: |
        mkdir -p data/traction
        echo "ticker,mentions,posts,comments,subreddits" > data/traction/test.csv
        echo "TEST,10,5,5,1" >> data/traction/test.csv
        
        echo "✅ Test data created"
        ls -la data/traction/
    
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-artifact-${{ github.run_number }}
        path: data/traction/test.csv
        retention-days: 1