name: Update NVDA Data

on:
  schedule:
    # Run weekly on Sunday at midnight
    # Note: Yahoo Finance only provides 15-minute data for the last 60 days
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install yfinance pandas
        
    - name: Download latest NVDA data
      run: |
        mkdir -p data
        python3 download_nvda_historical.py
        
    - name: Commit updated data
      uses: EndBug/add-and-commit@v9
      with:
        add: 'data/NVDA_15min_pattern_ready.csv'
        message: 'Update NVDA historical data'
        default_author: github_actions