name: Update NVDA Historical Data

on:
  schedule:
    # Run weekly on Sunday at midnight to append new data
    # Maintains a continuous 15-minute historical dataset
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install yfinance pandas azure-storage-blob python-dotenv
        
    - name: Update NVDA historical data
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_KEY: ${{ secrets.ACCESS_KEY }}
        AZURE_CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: |
        mkdir -p data
        
        # Update the historical data file by appending new data
        python3 update_historical_data.py